# Generated by Django 4.2.3 on 2023-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
